[package]
name = "ton-node-tools"
version = "0.1.0"
edition = "2018"
build = "common/build/build.rs"

[workspace]

[dependencies]
base64 = "0.11.0"
failure = "0.1.6"
hex = "0.4.2"
log = "0.4.11"
log4rs = "0.8.3"
serde = "1.0.105"
serde_json = "1.0.56"
shell-words = ""
clap = "2.33.3"

adnl = { version = "0.1", git = "https://github.com/tonlabs/ton-labs-adnl.git", features = ["client"] }
dht = { version = "0.1", git = "https://github.com/tonlabs/ton-labs-dht.git" }
overlay = { version = "0.1", git = "https://github.com/tonlabs/ton-labs-overlay.git" }
tokio = { version = "1.3.0", features = ["rt-multi-thread"] }
ton_api = { git = "https://github.com/tonlabs/ton-labs-tl.git", package = "ton_api" }
ton_block = { git = "https://github.com/tonlabs/ton-labs-block.git" }
ton_block_json = { git = "https://github.com/tonlabs/ton-labs-block-json.git" }
ton_node = { version = "0.5", git = "https://github.com/tonlabs/ton-labs-node.git" }
ton_types = { git = "https://github.com/tonlabs/ton-labs-types.git" }

[[bin]]
name = "adnl_resolve"
path = "bin/adnl_resolve.rs"

[[bin]]
name = "dhtscan"
path = "bin/dhtscan.rs"

[[bin]]
name = "gendht"
path = "bin/gendht.rs"

[[bin]]
name = "console"
path = "bin/console.rs"

[[bin]]
name = "keygen"
path = "bin/keygen.rs"

[[bin]]
name = "keyid"
path = "bin/keyid.rs"

[[bin]]
name = "print"
path = "bin/print.rs"

[[bin]]
name = "zerostate"
path = "bin/zerostate.rs"

[patch.'https://github.com/tonlabs/ton-labs-block.git']
ton_block = { git = "ssh://git@github.com/tonlabs/ton-block.git" }

[patch.'https://github.com/tonlabs/ton-labs-types.git']
ton_types = { git = "ssh://git@github.com/tonlabs/ton-types.git" }

[patch.'https://github.com/tonlabs/ton-labs-tl.git']
ton_api = { git = "ssh://git@github.com/tonlabs/ton-tl.git", package = "ton_api" }

[patch.'https://github.com/tonlabs/ton-labs-executor.git']
ton_executor = { git = "ssh://git@github.com/tonlabs/ton-executor.git" }

[patch.'https://github.com/tonlabs/ton-labs-node.git']
ton_node = { path = ".." }

[patch.'https://github.com/tonlabs/ton-labs-adnl.git']
adnl = { path = "../adnl" }

[patch.'https://github.com/tonlabs/ton-labs-dht.git']
dht = { path = "../dht" }

[patch.'https://github.com/tonlabs/ton-labs-overlay.git']
overlay = { path = "../overlay" }

[patch.'ssh://git@github.com/tonlabs/adnl.git']
adnl = { path = "../adnl" }

[patch.'ssh://git@github.com/tonlabs/dht.git']
dht = { path = "../dht" }

[patch.'ssh://git@github.com/tonlabs/overlay.git']
overlay = { path = "../overlay" }

[patch.'ssh://git@github.com/tonlabs/rldp.git']
rldp = { path = "../rldp" }
