[package]
build = 'common/build/build.rs'
edition = '2021'
name = 'ton-node-tools'
version = '0.1.291'

[[bin]]
name = 'adnl_resolve'
path = 'bin/adnl_resolve.rs'

[[bin]]
name = 'adnl_ping'
path = 'bin/adnl_ping.rs'

[[bin]]
name = 'dhtscan'
path = 'bin/dhtscan.rs'

[[bin]]
name = 'gendht'
path = 'bin/gendht.rs'

[[bin]]
name = 'console'
path = 'bin/console.rs'

[[bin]]
name = 'keygen'
path = 'bin/keygen.rs'

[[bin]]
name = 'keyid'
path = 'bin/keyid.rs'

[[bin]]
name = 'print'
path = 'bin/print.rs'

[[bin]]
name = 'zerostate'
path = 'bin/zerostate.rs'

[dependencies]
base64 = '0.13'
clap = '2.33.3'
failure = '0.1.6'
hex = '0.4.2'
log = '0.4.11'
log4rs = '1.1'
serde = '1.0.105'
serde_json = '1.0.56'
shell-words = '1.0.0'
adnl = { features = [ 'client' ], git = 'https://github.com/tonlabs/ton-labs-adnl', tag = '0.7.77' }
dht = { git = 'https://github.com/tonlabs/ton-labs-dht', tag = '0.5.74' }
ever-crypto = { git = 'https://github.com/tonlabs/ever-labs-crypto', branch = 'consensus-updates' }
overlay = { git = 'https://github.com/tonlabs/ton-labs-overlay', branch = 'consensus-updates' }
tokio = { features = [ 'rt-multi-thread' ], version = '1.5.0' }
ton_api = { git = 'https://github.com/tonlabs/ton-labs-tl', package = 'ton_api', branch = 'consensus-updates' }
ton_block = { git = 'https://github.com/tonlabs/ton-labs-block', branch = 'consensus-updates' }
ton_block_json = { git = 'https://github.com/tonlabs/ton-labs-block-json.git', branch = 'consensus-updates' }
ton_node = { git = 'https://github.com/tonlabs/ton-labs-node', branch = 'consensus-updates' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types', tag = '1.11.4' }

[features]
default = [ 'telemetry' ]
export_key = [ 'ever-crypto/export_key' ]
telemetry = [ 'adnl/telemetry', 'dht/telemetry', 'overlay/telemetry' ]
workchains = [ 'ton_node/workchains', 'ever-crypto/export_key' ]

[patch.'https://github.com/tonlabs/ton-labs-block.git']
ton_block = { git = 'https://github.com:443//tonlabs/ton-labs-block.git', branch = 'consensus-updates' }

[patch.'https://github.com/tonlabs/ton-labs-block-json.git']
ton_block_json = { git = 'https://github.com:443//tonlabs/ton-labs-block-json', branch = 'consensus-updates' }

[patch.'https://github.com/tonlabs/ton-labs-tl']
ton_api = { git = 'https://github.com:443//tonlabs/ton-labs-tl', package = 'ton_api', branch = 'consensus-updates' }

[patch.'https://github.com/tonlabs/ever-labs-crypto']
ever-crypto = { git = 'https://github.com:443//tonlabs/ever-labs-crypto', branch = 'consensus-updates' }

[patch.'https://github.com/tonlabs/ton-labs-vm']
ton_vm = { git = 'https://github.com:443//tonlabs/ton-labs-vm', branch = 'consensus-updates' }

[patch.'https://github.com/tonlabs/ton-labs-overlay']
overlay = { git = 'https://github.com:443//tonlabs/ton-labs-overlay', branch = 'consensus-updates' }
