[package]
build = 'common/build/build.rs'
edition = '2021'
name = 'ton-node-tools'
version = '0.1.287'


[[bin]]
name = 'adnl_resolve'
path = 'bin/adnl_resolve.rs'

[[bin]]
name = 'adnl_ping'
path = 'bin/adnl_ping.rs'

[[bin]]
name = 'dhtscan'
path = 'bin/dhtscan.rs'

[[bin]]
name = 'gendht'
path = 'bin/gendht.rs'

[[bin]]
name = 'console'
path = 'bin/console.rs'

[[bin]]
name = 'keygen'
path = 'bin/keygen.rs'

[[bin]]
name = 'keyid'
path = 'bin/keyid.rs'

[[bin]]
name = 'print'
path = 'bin/print.rs'

[[bin]]
name = 'zerostate'
path = 'bin/zerostate.rs'

[dependencies]
base64 = '0.13'
clap = '2.33.3'
failure = '0.1.6'
hex = '0.4.2'
log = '0.4.11'
log4rs = '1.1'
serde = '1.0.105'
serde_json = '1.0.56'
shell-words = '1.0.0'
adnl = { features = [ 'client' ], git = 'ssh://git@github.com/tonlabs/adnl.git' }
dht = { git = 'ssh://git@github.com/tonlabs/dht.git' }
ever-crypto = { git = 'ssh://git@github.com/tonlabs/ever-crypto.git' }
overlay = { git = 'ssh://git@github.com/tonlabs/overlay.git' }
tokio = { features = [ 'rt-multi-thread' ], version = '1.5.0' }
ton_api = { git = 'ssh://git@github.com/tonlabs/ton-tl.git', package = 'ton_api' }
ton_block = { git = 'ssh://git@github.com/tonlabs/ton-block.git' }
ton_block_json = { git = 'ssh://git@github.com/tonlabs/ton-block-json.git' }
ton_node = { git = 'ssh://git@github.com/tonlabs/ton-node.git' }
ton_types = { git = 'ssh://git@github.com/tonlabs/ton-types.git' }

[dev-dependencies]
async-trait = '0.1'
lockfree = { git = 'https://github.com/tonlabs/lockfree.git' }
storage = { git = 'ssh://git@github.com/tonlabs/ton-node.git', package = 'storage' }

[features]
default = [ 'telemetry' ]
export_key = [ 'ever-crypto/export_key' ]
telemetry = [ 'adnl/telemetry', 'dht/telemetry', 'overlay/telemetry' ]
workchains = [ 'ton_node/workchains', 'ever-crypto/export_key' ]

[patch.'https://github.com/tonlabs/ton-labs-block.git']
ton_block = { branch = 'feature-use-bls-key', git = 'ssh://git@github.com:22/tonlabs/ton-block.git' }
#ton_block = { path = '../ton-block' }

[patch.'ssh://git@github.com/tonlabs/ton-block.git']
ton_block = { branch = 'feature-use-bls-key', git = 'ssh://git@github.com:22/tonlabs/ton-block.git' }
#ton_block = { path = '../ton-block' }

[patch.'https://github.com/tonlabs/ton-labs-block-json.git']
ton_block_json = { branch = 'feature-use-bls-key', git = 'ssh://git@github.com:22/tonlabs/ton-block-json.git' }
#ton_block_json = { path = '../ton-block-json' }

[patch.'ssh://git@github.com/tonlabs/ton-block-json.git']
ton_block_json = { branch = 'feature-use-bls-key', git = 'ssh://git@github.com:22/tonlabs/ton-block-json.git' }
#ton_block_json = { path = '../ton-block-json' }

[patch.'https://github.com/tonlabs/ton-labs-executor.git']
ton_executor = { git = 'ssh://git@github.com/tonlabs/ton-executor.git' }

[patch.'https://github.com/tonlabs/ton-labs-types.git']
ton_types = { git = 'ssh://git@github.com/tonlabs/ton-types.git' }

[patch.'https://github.com/tonlabs/ton-labs-vm.git']
ton_vm = { branch = 'feature-use-bls-key', git = 'ssh://git@github.com:22/tonlabs/ton-vm.git' }

[patch.'ssh://git@github.com/tonlabs/ton-vm.git']
ton_vm = { branch = 'feature-use-bls-key', git = 'ssh://git@github.com:22/tonlabs/ton-vm.git' }

[patch.'ssh://git@github.com/tonlabs/ton-tl.git']
ton_api = { branch = 'feature-use-bls-keys', git = 'ssh://git@github.com:22/tonlabs/ton-tl.git', package = 'ton_api' }

[patch.'ssh://git@github.com/tonlabs/ever-crypto.git']
ever-crypto = { branch = 'feature-use-bls', git = 'ssh://git@github.com:22/tonlabs/ever-crypto.git' }

[patch.'https://github.com/tonlabs/ton-labs-node']
ton_node = { path = '../ton-node' }

[patch.'ssh://git@github.com/tonlabs/ton-node.git']
ton_node = { path = '../ton-node' }
