[package]
name = "ton-node-tools"
version = "0.1.0"
edition = "2018"

[dependencies]                                                
adnl = { git = "ssh://git@github.com/tonlabs/adnl.git" }
base64 = "0.11.0"
dht = { git = "ssh://git@github.com/tonlabs/dht.git" }
failure = "0.1.6"
overlay = { git = "ssh://git@github.com/tonlabs/overlay.git" }
tokio = { version = "0.2.5", features = ["rt-threaded", "udp"] }
ton_node = { git = "ssh://git@github.com/tonlabs/ton-node.git" }
ton_types = { git = "ssh://git@github.com/tonlabs/ton-types.git" }

[[bin]]
name = "keygen"
path = "src/keygen.rs"

[[bin]]
name = "dhtscan"
path = "src/dhtscan.rs"
